# Generated by Django 5.1.2 on 2024-11-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_first_name_alter_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='profile'),
        ),
        migrations.AlterField(
            model_name='account',
            name='resume',
            field=models.URLField(blank=True, null=True, verbose_name='resume'),
        ),
    ]
