# Generated by Django 5.1.2 on 2024-11-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobly', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
