# Generated by Django 5.1.2 on 2024-11-02 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobly', '0002_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('date_applied', models.DateField()),
                ('company', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AP', 'Applied'), ('AC', 'Accepted'), ('ASG', 'Assignment Given'), ('RJ', 'Rejected'), ('AD', 'Assignment Done'), ('IV', 'Interview')], default='AP', max_length=3)),
                ('JOB_URL', models.URLField(max_length=500)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
