# Generated by Django 5.1.2 on 2024-11-04 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobly', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_applied',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
