# Generated by Django 5.1.2 on 2024-11-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobly', '0004_alter_job_date_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='JOB_URL',
            new_name='job_url',
        ),
    ]
